name: Flask App Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    
    env:
      MODE: "dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir packages && pip install -r ./requirements.txt --target ./packages
          
      
      - uses: actions/upload-artifact@v2
        with:
          name: pip-packages
          path: ./packages
  build_image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: pip-packages
          path: ./packages
      - name: docker login
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: docker build
        run: docker build . -t ${DOCKER_USERNAME}/test:latest
 
      - name: docker push
        run: docker push ${DOCKER_USERNAME}/test:latest
  # build_push_image:
  # needs: build_artifact
  #  runs-on: ubuntu-latest
          
