name: Flask App Tests
env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    
    env:
      MODE: "dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Make package
        run: mkdir packages
      - name: Install requiremants
        run: pip install -r ./requirements.txt --target ./packages
      - name: Show all 
        run: ls -lah . && ls -lah ./packages
  
          
      
      - uses: actions/upload-artifact@v2
        with:
          name: pip-packages
          path: ./src/packages
  build_image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: pip-packages
          path: ./packages
      - name: docker login
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: docker build
        run: docker build . -t ${DOCKER_USERNAME}/test:latest
 
      - name: docker push
        run: docker push ${DOCKER_USERNAME}/test:latest
  # build_push_image:
  # needs: build_artifact
  #  runs-on: ubuntu-latest
          
